import 'package:flutter/material.dart';
import '../models/plant.dart';
import '../services/plant_service.dart';

class AddPlantPage extends StatefulWidget {
  @override
  _AddPlantPageState createState() => _AddPlantPageState();
}

class _AddPlantPageState extends State<AddPlantPage> {
  final _formKey = GlobalKey<FormState>();
  final _plantService = PlantService();

  String name = '';
  String imageUrl = '';
  String description = '';
  int minTemp = 0;
  int maxTemp = 0;
  int humidity = 0;
  bool isSensorConnected = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Add New Plant')),
      body: Padding(
        padding: EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: ListView(
            children: [
              TextFormField(
                decoration: InputDecoration(labelText: 'Name'),
                onChanged: (val) => name = val,
                validator: (val) => val!.isEmpty ? 'Enter name' : null,
              ),
              TextFormField(
                decoration: InputDecoration(labelText: 'Image URL'),
                onChanged: (val) => imageUrl = val,
              ),
              TextFormField(
                decoration: InputDecoration(labelText: 'Description'),
                onChanged: (val) => description = val,
              ),
              TextFormField(
                decoration: InputDecoration(labelText: 'Min Temp'),
                keyboardType: TextInputType.number,
                onChanged: (val) => minTemp = int.tryParse(val) ?? 0,
              ),
              TextFormField(
                decoration: InputDecoration(labelText: 'Max Temp'),
                keyboardType: TextInputType.number,
                onChanged: (val) => maxTemp = int.tryParse(val) ?? 0,
              ),
              TextFormField(
                decoration: InputDecoration(labelText: 'Humidity'),
                keyboardType: TextInputType.number,
                onChanged: (val) => humidity = int.tryParse(val) ?? 0,
              ),
              SwitchListTile(
                title: Text('Sensor Connected'),
                value: isSensorConnected,
                onChanged: (val) => setState(() => isSensorConnected = val),
              ),
              SizedBox(height: 20),
              ElevatedButton(
                child: Text('Add Plant'),
                onPressed: () async {
                  if (_formKey.currentState!.validate()) {
                    Plant plant = Plant(
                      id: '', // will be generated by MongoDB
                      name: name,
                      imageUrl: imageUrl,
                      description: description,
                      minTemp: minTemp,
                      maxTemp: maxTemp,
                      humidity: humidity,
                      isSensorConnected: isSensorConnected,
                    );
                    try {
                      Plant newPlant = await _plantService.addPlant(plant);
                      Navigator.pop(context, newPlant);
                    } catch (e) {
                      print(e);
                    }
                  }
                },
              )
            ],
          ),
        ),
      ),
    );
  }
}
